# Generated by Django 5.1.1 on 2024-09-24 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house_renting", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CarModel", models.CharField(max_length=255)),
                ("car_name", models.CharField(max_length=50)),
                ("available", models.BooleanField(default=True)),
                (
                    "rent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "sale_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("date_added", models.DateField(auto_now_add=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("main_image", models.ImageField(upload_to="cars/main/")),
                (
                    "landlord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="house_renting.landlord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=100)),
                ("user_email", models.EmailField(max_length=254)),
                ("user_contact_number", models.CharField(max_length=15)),
                ("message", models.TextField()),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="house_renting.car",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="cars/")),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="house_renting.car",
                    ),
                ),
            ],
        ),
    ]
