# Generated by Django 5.1.1 on 2024-09-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house_renting", "0002_car_carapplication_carimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="houses/videos/"),
        ),
        migrations.AddField(
            model_name="parcel",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="parcels/videos/"),
        ),
    ]
