# Generated by Django 5.1.1 on 2024-09-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house_renting", "0003_house_video_parcel_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="cars/videos/"),
        ),
    ]
